default_platform(:ios)

platform :ios do
  desc "앱스토어에 빌드 배포"
  lane :release do
    increment_build_number
    build_app(scheme: "Brawlytics")
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end
end
