# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-14  # Xcode 16이 설치된 macOS 환경
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 16
        run: sudo xcode-select -s /Applications/Xcode_16.0.app
      - name: Build
        run: xcodebuild -project Brawlytics.xcodeproj -scheme Brawlytics -configuration Debug build
